language: java
services:
  - mysql
before_install:
  - export TZ=Europe/Rome
  - mysql -u root --default-character-set=utf8 < ddl/ddl.sql
  - mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('root') WHERE user='root'; FLUSH PRIVILEGES;"
script:
  - mvn verify
